name: Recent-Law
markdown: kramdown
highlighter: rouge
plugins:
    - jekyll-sass
    - jekyll-haml
    - jekyll-minifier
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
