name: Recent-Law
markdown: redcarpet
highlighter: pygments
gems: [jekyll-sass]
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
